package com.pat.types

enum class FizzBuzzStatus {
    REQUEST_RECEIVED_SUCCESS,
    SAVED_TO_DATABASE_SUCCESS,
    SAVED_TO_DATABASE_FAILED,
    ORCHESTRATION_SERVICE_FAILED,
    TRANSFORM_FAILED,
    TRANSFORM_SUCCESS,
    COMPLETED,
    FAILED
}